DELETE FROM PRZEDMIOTY;
DELETE FROM KATEGORIE_TEMATYCZNE;
DELETE FROM CZESCI_KONSPEKTU;
DELETE FROM KIERUNKI;
DELETE FROM ELEMENTY_KONSPEKTU;

COMMIT;

DROP TRIGGER FKNTM_ELEMENTY_KONSPEKTU;
DROP SEQUENCE NR_KOLEJNY_SEQ;
DROP TABLE ELEMENTY_KONSPEKTU;
DROP TABLE CZESCI_KONSPEKTU;
DROP TABLE PRZEDMIOTY;
DROP TABLE KIERUNKI;
DROP TABLE KATEGORIE_TEMATYCZNE;

COMMIT;