INSERT INTO KIERUNKI VALUES ('AR', 'Automatyka i robotyka', '');
INSERT INTO KIERUNKI VALUES ('CB', 'Cyberbezpieczeństwo', '');
INSERT INTO KIERUNKI VALUES ('EL', 'Elektronika', '');
INSERT INTO KIERUNKI VALUES ('INF', 'Informatyka', '');
INSERT INTO KIERUNKI VALUES ('IBIO', 'Inżynieria biomedyczna', '');
INSERT INTO KIERUNKI VALUES ('IIR', 'Inżynieria internetu rzeczy', '');
INSERT INTO KIERUNKI VALUES ('TEL', 'Telekomunikacja', '');

COMMIT;

INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('MAT', 'Matematyka', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('AKSK', 'Architektura komputerów i sprzęt komputerowy', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('MWO', 'Metody wytwarzania oprogramowania', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('PI', 'Podstawy informatyki', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('FIZ', 'Fizyka', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('PSIOP', 'Przedmioty specjalności IOP', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('PSSZI', 'Przedmioty specjalności SZI', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('EL', 'Elektronika', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('INF', 'Informatyka', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('PPKAR', 'Przedmioty podstawowe kierunku AR', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('PET', 'Podstawy elektroniki i telekomunikacji', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('IT', 'Informatyka techniczna', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('TEL', 'Teleinformatyka', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('CB', 'Cyberbezpieczeństwo', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('POKCB', 'Przedmioty obieralne kierunku CB', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('FFPEF', 'Fizyka i fizyczne podstawy elektroniki i fotoniki', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('PEM', 'Podstawy elektroniki i miernictwo', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('TC', 'Technika cyfrowa', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('PIP', 'Podstawy informatyki i programowanie', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('POSEIF', 'Przedmioty obowiązkowe specjalności EIF', '');
INSERT INTO KATEGORIE_TEMATYCZNE VALUES ('POSEIM', 'Przedmioty obowiązkowe specjalności EIM', '');

COMMIT;

INSERT INTO PRZEDMIOTY VALUES ('AM', 'Analiza matematyczna', 'INF', 'MAT', '');
INSERT INTO PRZEDMIOTY VALUES ('MK1', 'Matematyka konkretna 1', 'INF', 'MAT', '');
INSERT INTO PRZEDMIOTY VALUES ('MK2', 'Matematyka konkretna 2', 'INF', 'MAT', '');
INSERT INTO PRZEDMIOTY VALUES ('PROB', 'Probabilistyka', 'INF', 'MAT', '');
INSERT INTO PRZEDMIOTY VALUES ('PTC', 'Podstawy techniki cyfrowej', 'INF', 'AKSK', '');
INSERT INTO PRZEDMIOTY VALUES ('AK', 'Architektura komputerów', 'INF', 'AKSK', '');
INSERT INTO PRZEDMIOTY VALUES ('WAE', 'Wstęp do automatyki i elektroniki', 'INF', 'AKSK', '');
INSERT INTO PRZEDMIOTY VALUES ('SKSKP', 'Systemy komputerowe w sterowaniu i pomiarach', 'INF', 'AKSK', '');
INSERT INTO PRZEDMIOTY VALUES ('PIP', 'Podstawy informatyki i programowania', 'INF', 'MWO', '');
INSERT INTO PRZEDMIOTY VALUES ('PZP', 'Projekt zespołowy pierwszy', 'INF', 'MWO', '');
INSERT INTO PRZEDMIOTY VALUES ('PO', 'Programowanie obiektowe', 'INF', 'MWO', '');
INSERT INTO PRZEDMIOTY VALUES ('PA', 'Programowanie aplikacyjne', 'INF', 'MWO', '');
INSERT INTO PRZEDMIOTY VALUES ('SWO', 'Sztuka wytwarzania oprogramowania', 'INF', 'MWO', '');
INSERT INTO PRZEDMIOTY VALUES ('PS', 'Programowanie sieciowe', 'INF', 'MWO', '');
INSERT INTO PRZEDMIOTY VALUES ('PZD', 'Projekt zespołowy drugi', 'INF', 'MWO', '');
INSERT INTO PRZEDMIOTY VALUES ('PP', 'Paradygmaty programowania', 'INF', 'MWO', '');
INSERT INTO PRZEDMIOTY VALUES ('ASD', 'Algorytmy i struktury danych', 'INF', 'PI', '');
INSERT INTO PRZEDMIOTY VALUES ('SK', 'Sieci komputerowe', 'INF', 'PI', '');
INSERT INTO PRZEDMIOTY VALUES ('WSI', 'Wprowadzenie do sztucznej inteligencji', 'INF', 'PI', '');
INSERT INTO PRZEDMIOTY VALUES ('SO', 'Systemy operacyjne', 'INF', 'PI', '');
INSERT INTO PRZEDMIOTY VALUES ('BD1', 'Bazy danych 1', 'INF', 'PI', '');
INSERT INTO PRZEDMIOTY VALUES ('WSZ', 'Wprowadzenie do systemów zarządzania', 'INF', 'PI', '');
INSERT INTO PRZEDMIOTY VALUES ('WM', 'Wstęp do multimediów', 'INF', 'PI', '');
INSERT INTO PRZEDMIOTY VALUES ('BSS', 'Bezpieczeństwo systemów i sieci', 'INF', 'PI', '');
INSERT INTO PRZEDMIOTY VALUES ('BD2', 'Bazy danych 2', 'INF', 'PI', '');
INSERT INTO PRZEDMIOTY VALUES ('FO', 'Fizyka ogólna', 'INF', 'FIZ', '');
INSERT INTO PRZEDMIOTY VALUES ('FPPI', 'Fizyczne podstawy przetwarzania informacji', 'INF', 'FIZ', '');
INSERT INTO PRZEDMIOTY VALUES ('ZPI', 'Zarządzanie projektami informatycznymi', 'INF', 'PSIOP', '');
INSERT INTO PRZEDMIOTY VALUES ('WUSI', 'Wdrażanie i utrzymanie systemów informatycznych', 'INF', 'PSIOP', '');
INSERT INTO PRZEDMIOTY VALUES ('TK', 'Techniki kompilacji', 'INF', 'PSIOP', '');
INSERT INTO PRZEDMIOTY VALUES ('POPT', 'Przeszukiwanie i optymalizacja', 'INF', 'PSSZI', '');
INSERT INTO PRZEDMIOTY VALUES ('SSN', 'Sztuczne sieci neuronowe', 'INF', 'PSSZI', '');
INSERT INTO PRZEDMIOTY VALUES ('UM', 'Uczenie maszynowe', 'INF', 'PSSZI', '');
INSERT INTO PRZEDMIOTY VALUES ('WMAT', 'Wstęp do matematyki', 'CB', 'MAT', '');
INSERT INTO PRZEDMIOTY VALUES ('AL', 'Analiza', 'CB', 'MAT', '');
INSERT INTO PRZEDMIOTY VALUES ('AGB', 'Algebra', 'CB', 'MAT', '');
INSERT INTO PRZEDMIOTY VALUES ('RP', 'Rachunek prawdopodobieństwa', 'CB', 'MAT', '');
INSERT INTO PRZEDMIOTY VALUES ('WF', 'Wstęp do fizyki', 'CB', 'FIZ', '');
INSERT INTO PRZEDMIOTY VALUES ('FPET', 'Fizyczne podstawy elektroniki i teleinformatyki', 'CB', 'FIZ', '');
INSERT INTO PRZEDMIOTY VALUES ('SPI', 'Szybkie prototypowanie inżynierskie', 'CB', 'PET', '');
INSERT INTO PRZEDMIOTY VALUES ('SSYS', 'Sygnały i systemy', 'CB', 'PET', '');
INSERT INTO PRZEDMIOTY VALUES ('EUE', 'Elementy i układy elektroniczne', 'CB', 'PET', '');
INSERT INTO PRZEDMIOTY VALUES ('TSMT', 'Transmisja sygnałów i media transmisyjne', 'CB', 'PET', '');
INSERT INTO PRZEDMIOTY VALUES ('AP1', 'Algorytmy i programowanie 1', 'CB', 'IT', '');
INSERT INTO PRZEDMIOTY VALUES ('SC', 'Systemy cyfrowe', 'CB', 'IT', '');
INSERT INTO PRZEDMIOTY VALUES ('AP2', 'Algorytmy i programowanie 2', 'CB', 'IT', '');
INSERT INTO PRZEDMIOTY VALUES ('BDBD', 'Bazy danych i Big Data', 'CB', 'IT', '');
INSERT INTO PRZEDMIOTY VALUES ('SKAP', 'Systemy komputerowe: architektura i programowanie', 'CB', 'IT', '');
INSERT INTO PRZEDMIOTY VALUES ('PUA', 'Projektowanie usług i aplikacji', 'CB', 'IT', '');
INSERT INTO PRZEDMIOTY VALUES ('KSSO', 'Komputerowe i sieciowe systemy operacyjne', 'CB', 'IT', '');
INSERT INTO PRZEDMIOTY VALUES ('UAI', 'Usługi i aplikacje Internetu', 'CB', 'TEL', '');
INSERT INTO PRZEDMIOTY VALUES ('SCT', 'Sieci i chmury teleinformatyczne', 'CB', 'TEL', '');
INSERT INTO PRZEDMIOTY VALUES ('KRI', 'Komutacja i routing w Internecie', 'CB', 'TEL', '');
INSERT INTO PRZEDMIOTY VALUES ('SMSIR', 'Sieci mobilne i sieci internetu rzeczy', 'CB', 'TEL', '');
INSERT INTO PRZEDMIOTY VALUES ('SLCD', 'Sieci lokalne i centra danych', 'CB', 'TEL', '');
INSERT INTO PRZEDMIOTY VALUES ('WCYB', 'Wprowadzenie do cyberbezpieczeństwa', 'CB', 'CB', '');
INSERT INTO PRZEDMIOTY VALUES ('BD', 'Bezpieczeństwo danych', 'CB', 'CB', '');
INSERT INTO PRZEDMIOTY VALUES ('BSO', 'Bezpieczeństwo systemów i oprogramowania', 'CB', 'CB', '');
INSERT INTO PRZEDMIOTY VALUES ('BK', 'Bezpieczeństwo komunikacji', 'CB', 'CB', '');
INSERT INTO PRZEDMIOTY VALUES ('KC', 'Kryminalistyka cyfrowa', 'CB', 'CB', '');
INSERT INTO PRZEDMIOTY VALUES ('BOS', 'Bezpieczeństwo organizacyjne i społeczne', 'CB', 'CB', '');

COMMIT;

INSERT INTO CZESCI_KONSPEKTU VALUES ('OP', DEFAULT, 'Opis');
INSERT INTO CZESCI_KONSPEKTU VALUES ('WYK', DEFAULT, 'Wykład');
INSERT INTO CZESCI_KONSPEKTU VALUES ('LAB', DEFAULT, 'Laboratorium');
INSERT INTO CZESCI_KONSPEKTU VALUES ('CW', DEFAULT, 'Ćwiczenia');
INSERT INTO CZESCI_KONSPEKTU VALUES ('LIT', DEFAULT, 'Literatura');
INSERT INTO CZESCI_KONSPEKTU VALUES ('MKO', DEFAULT, 'Metody i kryteria oceniania');

COMMIT;

INSERT INTO ELEMENTY_KONSPEKTU VALUES ('AM', 'OP', 'Głównym celem przedmiotu jest zapoznanie studentów z podstawami rachunku różniczkowego');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('AM', 'CW', 'Podczas ćwiczeń audytoryjnych omawiane będą kolejno zadania');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('AM', 'LIT', 'R. Rudnicki, Wykłady z analizy matematycznej, PWN 2001');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('PTC', 'OP', 'Celem przedmiotu jest przedstawienie metod projektowania układów cyfrowych');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('PTC', 'LAB', 'Podstawowe układy kombinacyjne.');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('PTC', 'LIT', 'Skorupski A.: Podstawy techniki cyfrowej, WKŁ, Warszawa, 2004');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('PTC', 'MKO', 'ocenę wiedzy i umiejętności wykazanych na egzaminie pisemnym o charakterze problemowym');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('BSS', 'OP', 'Głównym celem przedmiotu jest uświadomienie słuchaczom, z jakimi zagrożeniami ma do czynienia dzisiejszy użytkownik Internetu');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('BSS', 'LAB', 'W ramach laboratoriów studenci praktycznie zapoznają się z omawianymi na wykładzie zagadnieniami podczas ich konfiguracji');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('BSS', 'LIT', 'Niebezpiecznik, https://niebezpiecznik.pl/');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('BSS', 'MKO', 'ocenę wiedzy i umiejętności wykazanych na egzaminie pisemnym o charakterze problemowym');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('FO', 'OP', 'Celem przedmiotu jest zapoznanie studentów z podstawami mechaniki klasycznej');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('FO', 'WYK', '1. Drgania 2. Fale 3. Teoria pola 4. Pole elektryczne');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('FO', 'CW', 'Ruch drgający, oscylator harmoniczny, rezonans');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('FO', 'LAB', 'Numeryczne rozwiązanie równania falowego');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('FO', 'LIT', 'D. Halliday, R. Resnick, J. Walker, Podstawy fizyki, t.1-4, Wyd. Naukowe PWN');
INSERT INTO ELEMENTY_KONSPEKTU VALUES ('FO', 'MKO', 'ocenę wiedzy i umiejętności wykazanych na egzaminie pisemnym o charakterze problemowym');


COMMIT;
